### ISSUE TITLE
linker failures with Ubuntu 22.04 container

### ISSUE THREAD

**Issue by mythi** [intel/qpl#11]
I'm building qpl in a Ubuntu 20.04 container. When moving to 22.04, the build fails:

```
[ 95%] Linking CXX executable stress_thread_tests
/usr/bin/ld: CMakeFiles/stress_thread_tests.dir/compressor_stress_test.cpp.o: in function `qpl::test::details::test(unsigned int)':
compressor_stress_test.cpp:(.text+0x2f1): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::thread::id)'
/usr/bin/ld: compressor_stress_test.cpp:(.text+0x3c5): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::thread::id)'
/usr/bin/ld: compressor_stress_test.cpp:(.text+0x417): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::thread::id)'
/usr/bin/ld: compressor_stress_test.cpp:(.text+0x501): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::thread::id)'
/usr/bin/ld: compressor_stress_test.cpp:(.text+0x553): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::thread::id)'
/usr/bin/ld: CMakeFiles/stress_thread_tests.dir/compressor_stress_test.cpp.o:compressor_stress_test.cpp:(.text+0x5c1): more undefined references to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::thread::id)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [tools/tests/thread_tests/stress/CMakeFiles/stress_thread_tests.dir/build.make:214: tools/tests/thread_tests/stress/stress_thread_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:1884: tools/tests/thread_tests/stress/CMakeFiles/stress_thread_tests.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by mzhukova** [comment]
Hi @mythi what QPL version are you using? 
Could you please provide an output of the `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<install_dir> ..` (or similar) step, so that we could better understand if all the necessary tools were found during setup?

**Comment by mythi** [comment]
both 0.2.0 and 0.3.0 are failing. The Dockerfile is here https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/demo/iaa-qpl-demo/Dockerfile (changing 20.04 to 22.04 makes it fail)

**Comment by mythi** [comment]
@mzhukova were you able to reproduce?

**Comment by mythi** [comment]
Also v1.0.0 is failing but the error is different (benchmarks fail to build)

**Comment by mythi** [comment]
With 

```
sed -i '10i #include <stdexcept>' tools/benchmarks/include/types.hpp
```

I have the build passing when using v1.0.0.

**Comment by mzhukova** [comment]
Hi @mythi, apologies for the delayed reply, I was on vacation.

So far I was not able to reproduce the build issue that you see, however I've just used clang-tidy on v1.0.0 and I see that benchmarks are missing two headers in `tools/benchmarks/include/types.hpp`:
```
 #include <cstdint>
+#include <string>
+#include <vector>
```
and also one more in `tools/benchmarks/include/utility.hpp`:
```
 #include <details/utility.hpp>
+#include <string>
 #include "cmd_decl.hpp"
```

Would it be possible for you to double check that this would fix the issue on your side? and I'll prepare a PR meanwhile.

**Comment by mythi** [comment]
> benchmarks are missing two headers in tools/benchmarks/include/types.hpp:

@mzhukova I can try that on Thursday but for me this alone helped:

```
 #include <cstdint>
+#include <stdexcept>
```

**Comment by mzhukova** [comment]
Hi @mythi, just an update on this -- I was able to reproduce build issue, so we will be fixing it shortly.

**Comment by mzhukova** [comment]
Hello again @mythi please, check the latest develop once you have time and let me know if the issue is resolved!

**Comment by mythi** [comment]
@mzhukova thanks! I can confirm the latest `develop` works fine in my environment (Ubuntu 22.04 container). I did not check with Ubuntu 20.04 anymore.

**Comment by mzhukova** [comment]
Thanks for the confirmation @mythi, I'll be closing the issue then!
Are you fine with using a develop or would you prefer a 1.0.1 tag created at some point?

**Comment by mythi** [comment]
> Are you fine with using a develop or would you prefer a 1.0.1 tag created at some point?

I'd prefer a `v1.0.1` tag at some point but I'm not blocked by this right now. My [fix](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/b534c167118bfaa089377854f035d31428bc2549/demo/iaa-qpl-demo/Dockerfile#L33-L38)

**Comment by mzhukova** [comment]
> > Are you fine with using a develop or would you prefer a 1.0.1 tag created at some point?
> 
> I'd prefer a `v1.0.1` tag at some point but I'm not blocked by this right now. My [fix](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/b534c167118bfaa089377854f035d31428bc2549/demo/iaa-qpl-demo/Dockerfile#L33-L38)

Thanks! I'll let you know when 1.0.1 will be available, so that we can remove the w/a. I'll keep the issue open till then.

**Comment by mzhukova** [comment]
Hi @mythi we've released QPL 1.1.0 that includes the fix, please let me know if it works for you, so that I can close the issue :)

**Comment by mythi** [comment]
> Hi @mythi we've released QPL 1.1.0 that includes the fix, please let me know if it works for you, so that I can close the issue :)

Thanks! I asked @ozhuraki to verify

**Comment by mzhukova** [comment]
Hi @mythi, do you have any update? could we close the issue?

**Comment by mythi** [comment]
> Hi @mythi, do you have any update? could we close the issue?

@ozhuraki confirmed the build is OK.
