### ISSUE TITLE
High Level API has been dropped

### ISSUE THREAD

**Issue by Arvinos** [intel/qpl#13]
High Level API is the most poverful and extendable API of QPL. In perspective it is the best way to support IAA without user affection. JobAPI is ugle, not threadsafe and doesnt extendable without user affection and require a lot of memmory to keep JobAPI structure. 

Moreover High level API was designed to resolve QPL workflow during compile time. In the first implementation it showed x1.5 performance grow in comparison with JobAPI, without microarhitectural optimisation. 

In the long perspective, High level API must been replace Job API as library primary interface. I am sad that we didnt completed our goal.

PS. std runtime for C++ for C libraries is bad way. It will drop user expectations from the library.

**Comment by mzhukova** [comment]
Hi @Arvinos, 
Thanks for the feedback, I do understand your point. However, High-Level API was not considered complete in the timeframe of major release, so the team had to make a call. It doesn't mean though that in the future Job API will stay the same and won't be converted to something resembling previous HL API model, or that for instance we won't re-introduce HL API. Your previous work is greatly appreciated and not lost.

As for C++-runtime, it is indeed not an ideal situation, but this dependency didn't appear with the latest commits btw, and if issue appears this would be re-worked of course.

**Comment by Arvinos** [comment]
Thanks for the answer. I hope, we will see that our work, ideas be completed at full. 

Job API must die)
