### ISSUE TITLE
install issue for v1.1.0 brach

### ISSUE THREAD

**Issue by Sean58238** [intel/qpl#18]
**Steps：**
 git clone --recursive https://github.com/intel/qpl.git
 cd qpl
 git checkout v1.1.0
 mkdir build & cd build
 cmake -DCMAKE_BUILD_TYPE=Release .. 
 make

**error log**
[ 80%] Building CXX object tools/tests/functional/algorithmic_tests/CMakeFiles/algorithmic_tests.dir/low_level_api/aggregates.cpp.o
In file included from /home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/../../../common/analytic_fixture.hpp:17,
                 from /home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/aggregates.cpp:8:
/home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/../../../common/test_cases.hpp:207:9: error: ISO C++ forbids declaration of ‘GTEST_DISALLOW_COPY_AND_ASSIGN_’ with no type [-fpermissive]
  207 |         GTEST_DISALLOW_COPY_AND_ASSIGN_(GTEST_TEST_CLASS_NAME_(test_suite_name,   \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/ta_ll_common.hpp:22:5: note: in expansion of macro ‘QPL_TEST_TC_’
   22 |     QPL_TEST_TC_(ta##_c_api_##operation, test, test_fixture, testing::internal::GetTypeId<test_fixture>())
      |     ^~~~~~~~~~~~
/home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/aggregates.cpp:78:5: note: in expansion of macro ‘QPL_LOW_LEVEL_API_ALGORITHMIC_TEST_TC’
   78 |     QPL_LOW_LEVEL_API_ALGORITHMIC_TEST_TC(aggregates, min_max_sum, MinMaxSumTest)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/../../../common/test_cases.hpp:209:9: error: ISO C++ forbids declaration of ‘GTEST_DISALLOW_MOVE_AND_ASSIGN_’ with no type [-fpermissive]
  209 |         GTEST_DISALLOW_MOVE_AND_ASSIGN_(GTEST_TEST_CLASS_NAME_(test_suite_name,   \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/ta_ll_common.hpp:22:5: note: in expansion of macro ‘QPL_TEST_TC_’
   22 |     QPL_TEST_TC_(ta##_c_api_##operation, test, test_fixture, testing::internal::GetTypeId<test_fixture>())
      |     ^~~~~~~~~~~~
/home/sean/iaa/qpl/tools/tests/functional/algorithmic_tests/low_level_api/aggregates.cpp:78:5: note: in expansion of macro ‘QPL_LOW_LEVEL_API_ALGORITHMIC_TEST_TC’
   78 |     QPL_LOW_LEVEL_API_ALGORITHMIC_TEST_TC(aggregates, min_max_sum, MinMaxSumTest)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [tools/tests/functional/algorithmic_tests/CMakeFiles/algorithmic_tests.dir/build.make:76: tools/tests/functional/algorithmic_tests/CMakeFiles/algorithmic_tests.dir/low_level_api/aggregates.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1383: tools/tests/functional/algorithmic_tests/CMakeFiles/algorithmic_tests.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

**Comment by mzhukova** [comment]
Hi @Sean58238 Could you please let me know what compiler/OS you're using? So that I could try to reproduce the behavior.

**Comment by mzhukova** [comment]
NVM, I think I know what the problems is --
we've updated submodules, and I think when you checked out 1.1.0 tag you didn't update the submodule to the corresponding version (I believe you may see something like `modified:  tools/third-party/google-test (new commits)` when you checkout v1.1.0 after cloning repo).

So after `git checkout v1.1.0`, could you please do:
```
git submodule update
```
and try building again?

**Comment by Sean58238** [comment]
Tried, the The reason is google-test version, Thanks a lot!
