### ISSUE TITLE
issue about block_on_fault

### ISSUE THREAD

**Issue by Sean58238** [intel/qpl#19]
In historical versions，QPL support the BoF(block_on_fault) disabled, but not support in latest version.  
For example:  
The RocksDB IAA plugin and QPL assume page faults are handled by the hardware. If disable BoF will cause error：corrupted compressed block contents。

Does QPL will support the "BoF disable" in an upcoming version? If not what's the reason?

**Comment by mzhukova** [comment]
Hi @Sean58238,
What exactly do you mean by QPL does not support Block On Fault?

Essentially, what QPL does is always respect BOF setting on the accelerator on hardware path (as you could see at https://github.com/intel/qpl/blob/develop/sources/middle-layer/dispatcher/hw_device.cpp#L66).

**Comment by Sean58238** [comment]
Thank you, it's clear now.
All the configuration files provided by QPL have BOF set to 1 (see https://github.com/intel/qpl/blob/develop/tools/configs/1n1d1e1w-s-n1.conf#L14).
