### ISSUE TITLE
who and how to use QPL library?

### ISSUE THREAD

**Issue by Pinpiew** [intel/qpl#2]
I means which application or library will use QPL library. is there some software stack to describe the position of the QPL.

**Comment by mzhukova** [comment]
Hi @Pinpiew, thank you for you interest in Intel® Query Processing Library!

Intel® QPL is a new library that basically provides APIs to communicate with Intel® In-Memory Analytics Accelerator (Intel® IAA). If you want more details on the architecture of the Intel® IAA, you could find the full specification on intel.com.

Essentially applications with a huge volume of data would benefit from using this library. The good example here would be Database managements systems. For instance, you could find the initial integration of Intel® QPL that has been recently added to [ClickHouse®](https://clickhouse.com/docs/en/whats-new/changelog/#performance-improvement)

Please, let me know if you have any other questions regarding the library or its usage.

Best,
Maria

**Comment by Pinpiew** [comment]
I see, and no any other questions. thanks!
