### ISSUE TITLE
qpl_execute_job returns 206 or 204 when runing decompress operation

### ISSUE THREAD

**Issue by cfzhu** [intel/qpl#21]
hi, I'm integrating qat compression and iAA decompression，QPL can decompress most of the data compressed by qat，only a small percentage of data blocks cannot be decompressed by the QPL with qpl_path_hardware, it returns error codes “204“ or ”206”,  but zlib or qpl with qpl_path_software can decompress it successfully. Could you tell me the reason of this issue?

**Comment by mzhukova** [comment]
Closed per offline discussion.
