### ISSUE TITLE
Question about parquet rle parser

### ISSUE THREAD

**Issue by jhorstmann** [intel/qpl#22]
The [parquet rle format parser](https://intel.github.io/qpl/documentation/dev_guide_docs/c_use_cases/c_operations_parsers.html) is described as taking the bitwidth from the first byte of the input:

> If the parser is specified as [qpl_parser.qpl_p_parquet_rle](https://intel.github.io/qpl/documentation/dev_ref_docs/c_ref/c_common_definitions.html#c.qpl_parser.qpl_p_parquet_rle), it is viewed as being in Parquet RLE format. In this case, the bit width is given in the data stream, so [qpl_job.src1_bit_width](https://intel.github.io/qpl/documentation/dev_ref_docs/c_ref/c_job_apis.html#c.qpl_job.src1_bit_width) must be set to 0.

From my understanding of the parquet format this prefixing with the bit width is specific to the [encoding of dictionary data pages](https://github.com/apache/parquet-format/blob/master/Encodings.md#dictionary-encoding-plain_dictionary--2-and-rle_dictionary--8). The repetition and definition levels that precede this data determine their bitwidth based on the maximum level, which is stored separately in metadata.

So my question would if the rle parser can still be used to speed up decoding of repetition and definition levels, or whether a separate implementation has to be used for those.

**Comment by abdelrahim-hentabli** [comment]
Hey @jhorstmann , our [parquet rle format](https://intel.github.io/qpl/documentation/dev_guide_docs/c_use_cases/filter_ops/c_operations_parsers.html#parquet-rle-format) is more closely related to Apache's [Run Length Encoding / Bit-Packing Hybrid format](https://github.com/apache/parquet-format/blob/master/Encodings.md#run-length-encoding--bit-packing-hybrid-rle--3). 

QPL only deals with flat parquet schemas, and so doesn't take into account repetition and definition levels. So a [separate implementation](https://blog.twitter.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet) would need to be used to flatten a nested structure.

**Comment by mzhukova** [comment]
Hi @jhorstmann do you have any further questions or could we close the issue as resolved?

**Comment by jhorstmann** [comment]
Thank you, that answered my question!
