### ISSUE TITLE
ok to execute "ll_cpp_compression_example software_path", but core dumped at "/ll_cpp_compression_example hardware_path"

### ISSUE THREAD

**Issue by happyvera1115** [intel/qpl#25]
Dear,
could you please give me some advice about how to execute "./ll_cpp_compression_example hardware_path" successfully?

================
# ./ll_cpp_compression_example software_path
The example will be run on the software path.
Content was successfully compressed and decompressed.
Compressed size: 20
=============
# ./ll_cpp_compression_example hardware_path
The example will be run on the hardware path.
qpl-diag: Intel QPL version 1.2.0
qpl-diag: loading driver: libaccel-config.so.1
terminate called after throwing an instance of 'std::runtime_error'
  what():  An error acquired during compression job initializing.
Aborted (core dumped)

===============
bios setting: follow IAA user guide

grub setting:
# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.2.0-31-generic root=UUID=e84f2c14-d73c-4911-adb4-848f4664bc70 ro console=ttyS0,115200n8 console=tty0 biosdevname=0 net.ifnames=0 modprobe.blacklist=ipmi_ssif,qat_c62x,qat_dh895xcc,qat_c3xxx,qat_c4xxx,qat_4xxx,intel_qat,ucsi_acpi,nouveau selinux=0 consoleblank=0 intel_idle.max_cstate=0 intel_pstate=disable printk.devkmsg=on iomem=relaxed intel_iommu=on,sm_on

OS: Ubuntu23.04_1.07.006 [kernel 6.2.0-31-generic]

idxd driver: 
# modinfo idxd
filename:       /lib/modules/6.2.0-31-generic/kernel/drivers/dma/idxd/idxd.ko
import_ns:      IDXD
author:         Intel Corporation
license:        GPL v2
version:        1.00
QPL version: 1.2.0
====
ok to find iax device.
# find / -name iax*
/sys/devices/iax1
/sys/devices/pci0000:f2/0000:f2:02.0/iax1
/sys/devices/pci0000:f2/0000:f2:02.0/iax1/wq1.0/iax!wq1.0
/sys/bus/event_source/devices/iax1
/dev/iax

**Comment by mzhukova** [comment]
Hello @happyvera1115, could you please print out the status value at https://github.com/intel/qpl/blob/develop/examples/low-level-api/compression_example.cpp#L60 (as it seems to be the place where exception is happening based on your description)?
Also, could you please double check that you have `libaccel-config.so.1` available either in standard location or in `LD_LIBRARY_PATH`?

**Comment by happyvera1115** [comment]
Thanks mzhukova..
This issue is solved by Oakley yesterday.
after having cmd "ldconfig /usr/lib64" in my system, this phenomenon is gone and no core dump error occurred.

**Comment by mzhukova** [comment]
glad it got resolved @happyvera1115, please let us know if you would need further help :)
