### ISSUE TITLE
Unable to run compression_example.cpp with hardware path

### ISSUE THREAD

**Issue by raunaks13** [intel/qpl#26]
I am using an Intel(R) Xeon(R) Platinum 8460H machine with Ubuntu 22.04 LTS.
I built QPL and I am able to run the compression example on `~/qpl_library/examples/low-level-api/examples/compression_example.cpp` with the software path.

However with the hardware path when I compile and run:
```
g++ -I/home/raunaks3/qpl_library/qpl_installation/include -o compression_example compression_example.cpp /home/raunaks3/qpl_library/qpl_installation/lib/libqpl.a -ldl
./compression_example
```
 I am getting: 
```
The example will be run on the hardware path.
terminate called after throwing an instance of 'std::runtime_error'
  what():  An error acquired during compression job initializing.
Aborted (core dumped)
```
The status of this error is 503.

I have built the library with default settings and tried configuring the device with both `accel-conf.py` and `accel-config`, which seem to show that dsa0 is enabled.
`libaccel-config.so` and `libaccel-config.so.1` are both present in `/usr/lib64/`.
What could be the reason for the issue?

**Comment by mzhukova** [comment]
hi @raunaks13, 
> which seem to show that dsa0 is enabled. 

Did you mean that IAA (`iax`) is available or could you please double check was was enabled on the host? 
Also, using accelerator requires elevated permission, so you could either retry running with sudo or you need to get a user access for `/dev/iax<X>/wq.<Y>.<Z>`, where `X, Y, Z` describes all configured devices and work queues.

**Comment by raunaks13** [comment]
@mzhukova thanks for your response. I think I was using the wrong config file from `share/QPL/configs/`. 
I tried with `1n1d1e1w-s-n2.conf` and it's working now.
I had another slightly related question - how would you recommend choosing the number of nodes, devices, engines, and workqueues? And how would these affect performance?
