### ISSUE TITLE
Issues in using the hardware path with IAA

### ISSUE THREAD

**Issue by raunaks13** [intel/qpl#28]
I am using an Intel(R) Xeon(R) Platinum 8460H machine with Ubuntu 22.04 LTS.
I built QPL and I am able to run the compression example on `~/qpl_library/examples/low-level-api/examples/compression_example.cpp` with the software path.

However with the hardware path when I compile and run:

```
g++ -I/home/raunaks3/qpl_library/qpl_installation/include -o compression_example compression_example.cpp /home/raunaks3/qpl_library/qpl_installation/lib/libqpl.a -ldl
sudo ./compression_example hardware_path
```
I am getting:
```
The example will be run on the hardware path.
An error 503 acquired during job initializing.
```
When I run `sudo accel-config list` this is the output:
```[
  {
    "dev":"iax1",
    "max_groups":4,
    "max_work_queues":8,
    "max_engines":8,
    "work_queue_size":128,
    "numa_node":0,
    "op_cap":"00000000,00000000,00000000,00000000,00000000,007f331c,00000000,0000000d",
    "gen_cap":"0x71f10901f0105",
    "version":"0x100",
    "state":"enabled",
    "max_batch_size":-2,
    "max_transfer_size":2147483648,
    "configurable":1,
    "pasid_enabled":1,
    "cdev_major":510,
    "clients":0,
    "groups":[
      {
        "dev":"group1.0",
        "traffic_class_a":1,
        "traffic_class_b":1,
        "grouped_workqueues":[
          {
            "dev":"wq1.0",
            "mode":"shared",
            "size":128,
            "group_id":0,
            "priority":10,
            "block_on_fault":1,
            "max_batch_size":-2,
            "max_transfer_size":2147483648,
            "cdev_minor":0,
            "type":"user",
            "name":"app1",
            "threshold":128,
            "ats_disable":0,
            "state":"enabled",
            "clients":0
          }
        ],
        "grouped_engines":[
          {
            "dev":"engine1.0",
            "group_id":0
          },
          {
            "dev":"engine1.1",
            "group_id":0
          },
          {
            "dev":"engine1.2",
            "group_id":0
          },
          {
            "dev":"engine1.3",
            "group_id":0
          },
          {
            "dev":"engine1.4",
            "group_id":0
          },
          {
            "dev":"engine1.5",
            "group_id":0
          },
          {
            "dev":"engine1.6",
            "group_id":0
          },
          {
            "dev":"engine1.7",
            "group_id":0
          }
        ]
      },
      {
        "dev":"group1.1",
        "traffic_class_a":1,
        "traffic_class_b":1
      },
      {
        "dev":"group1.2",
        "traffic_class_a":1,
        "traffic_class_b":1
      },
      {
        "dev":"group1.3",
        "traffic_class_a":1,
        "traffic_class_b":1
      }
    ]
  }
]
```

iax1 seems to be enabled. What could be the reason for the issue?

**Comment by mzhukova** [comment]
Could you please make sure that you either pinned the process to the NUMA node of the calling thread or set `job->numa_id` to the NUMA id that has iax1? As per [NUMA support documentation](https://intel.github.io/qpl/documentation/introduction_docs/introduction.html#numa-support).

**Comment by raunaks13** [comment]
@mzhukova I tried adding `job->numa_id = 0;` before `status = qpl_init_job(execution_path, job);`
and then running `numactl --membind=0 --cpunodebind=0 ./compression_example hardware_path`
but I am getting the same message
```
The example will be run on the hardware path.
An error 503 acquired during job initializing.
```

**Comment by mzhukova** [comment]
Hi @raunaks13, sorry for the delayed response.
Could you please let me know if the issue got resolved on your side?

**Comment by mzhukova** [comment]
Closing as no reply, please feel free to re-open if you're still facing this issue.

**Comment by Sean58238** [comment]
@mzhukova  we also get the report from customer similar above issue, following are the logs, and I didn't reproduce this issue in BKC OS and kernel.  Please give some comments.

Host Name:            debian
Kernel:               5.18.0

root@debian:/home/new/qpl/build/bin# lspci | grep -i 0b25
00:01.0 System peripheral: Intel Corporation Device 0b25
05:01.0 System peripheral: Intel Corporation Device 0b25
0a:01.0 System peripheral: Intel Corporation Device 0b25
0f:01.0 System peripheral: Intel Corporation Device 0b25
80:01.0 System peripheral: Intel Corporation Device 0b25
85:01.0 System peripheral: Intel Corporation Device 0b25
8a:01.0 System peripheral: Intel Corporation Device 0b25
8f:01.0 System peripheral: Intel Corporation Device 0b25
root@debian:/home/new/qpl/build/bin# lspci -vvvs 00:01.0 | grep -e 'PASIDCtl' -e 'PRICtl' -e 'ATSCtl'
                ATSCtl: Enable+, Smallest Translation Unit: 00
                PASIDCtl: Enable+ Exec- Priv+
                PRICtl: Enable+ Reset-
root@debian:/home/new/qpl/build/bin#

root@debian: wq_size=128
root@debian: accel-config config-engine iax1/engine1.0 --group-id=0
root@debian: accel-config config-engine iax1/engine1.1 --group-id=0
root@debian: accel-config config-engine iax1/engine1.2 --group-id=0
root@debian: accel-config config-engine iax1/engine1.3 --group-id=0
root@debian: accel-config config-engine iax1/engine1.4 --group-id=0
root@debian: accel-config config-engine iax1/engine1.5 --group-id=0
root@debian: accel-config config-engine iax1/engine1.6 --group-id=0
root@debian: accel-config config-engine iax1/engine1.7 --group-id=0
root@debian: accel-config config-wq iax1/wq1.0 -g 0 -s 128 -p 10 -m "shared" -y user -n user1 -t 128 -b 1 -d user
root@debian: accel-config enable-device iax1
enabled 1 device(s) out of 1
root@debian: accel-config enable-wq iax1/wq1.0
enabled 1 wq(s) out of 1
root@debian: accel-config list

  {
    "dev":"iax1",
    "max_groups":4,
    "max_work_queues":16,
    "max_engines":8,
    "work_queue_size":256,
    "numa_node":0,
    "gen_cap":"0x171f20901f5315",
    "version":"0x200",
    "state":"enabled",
    "max_batch_size":1,
    "max_transfer_size":2147483648,
    "configurable":1,
    "pasid_enabled":1,
    "cdev_major":243,
    "clients":0,
    "groups":[
      {
        "dev":"group1.0",
        "grouped_workqueues":[
          {
            "dev":"wq1.0",
            "mode":"shared",
            "size":128,
            "group_id":0,
            "priority":10,
            "block_on_fault":1,
            "max_batch_size":32,
            "max_transfer_size":2097152,
            "cdev_minor":0,
            "type":"user",
            "name":"user1",
            "threshold":128,
            "ats_disable":0,
            "state":"enabled",
            "clients":0
          }
        ],
        "grouped_engines":[
          {
            "dev":"engine1.0",
            "group_id":0
          },
          {
            "dev":"engine1.1",
            "group_id":0
          },
          {
            "dev":"engine1.2",
            "group_id":0
          },
          {
            "dev":"engine1.3",
            "group_id":0
          },
          {
            "dev":"engine1.4",
            "group_id":0
          },
          {
            "dev":"engine1.5",
            "group_id":0
          },
          {
            "dev":"engine1.6",
            "group_id":0
          },
          {
            "dev":"engine1.7",
            "group_id":0
          }
        ]
      },
      {
        "dev":"group1.1"
      },
      {
        "dev":"group1.2"
      },
      {
        "dev":"group1.3"
      }
    ]
  }

root@debian:~# cd /home/new/
root@debian:/home/new# cd qpl
root@debian:/home/new/qpl# find / -name "qpl_benchmarks"
/home/new/qpl/build/bin/qpl_benchmarks
/home/new/qpl/build/tools/benchmarks/qpl_benchmarks
root@debian:/home/new/qpl/build/bin# numactl --membind=0 --cpunodebind=0 ./qpl_benchmarks --dataset=./iaa_throughput_dataset  --benchmar_filter="deflate.*:c/.*:iaa.*:sync.*:pic.113.*:fixed/lvl:1.*" --benchmark_min_time=0.5 --block_size=4096 --queue_size=1 --threads=1
Host Name:            debian
Kernel:               5.18.0
CPU:                  GENUINE INTEL(R) XEON(R) (173)
    Microcode:        0x80000593
    Stepping:         0
    Logical Cores:    384
    Physical Cores:   192
    Cores per Socket: 96
    Sockets:          2
Accelerators:         0
terminate called after throwing an instance of 'std::runtime_error'
 what():  hw init failed in qpl_init_job
Aborted
root@debian:/home/new/qpl/build/bin#

**Comment by mcao59** [comment]
@Sean58238 Could you ask the customer to try adding `sudo` to the command? Like the example command in https://intel.github.io/qpl/documentation/bench_docs/guide.html#throughput-tests
As mentioned in [QPL documentation](https://intel.github.io/qpl/documentation/get_started_docs/quick_start.html): Either sudo privileges or elevated permissions are required to initialize Intel QPL job with hardware_path.

**Comment by DonMichaelCorleone** [comment]
I also have the same issue. When I try to run any of the examples with the hardware_path I get 
`An error 503 acquired during job initializing.`
I run the binary as a root user and the accelerator is active and configured. I am also running this in AWS m7i.metal-24xl instance. I would really appreciate some help. Thanks :)
