### ISSUE TITLE
Is Decryption/Encryption on the Roadmap?

### ISSUE THREAD

**Issue by Jonas-Heinrich** [intel/qpl#29]
Hi,

Inflation and filter operations can already be fused in QPL with `QPL_FLAG_DECOMPRESS_ENABLE` AFAIK. According to the IAA architecture specification however, it should also be possible to further "fuse" decryption, inflation and filter operations into a single device invocation. 

If I understand QPL's documentation correctly, the IAA encryption/decryption operations are not supported in QPL at this time. Is this feature planned?

Thanks,
Jonas

**Comment by mzhukova** [comment]
Hi @Jonas-Heinrich, you're right, IAA allows for fusing of these operations, however QPL does not support encryption/decryption, and, as of today, there are no plans on introducing support in the nearest future.

**Comment by Jonas-Heinrich** [comment]
Alright, thank you for the clarification!
