### ISSUE TITLE
Does libqpl support being built as a .so file?

### ISSUE THREAD

**Issue by hsiangkao** [intel/qpl#31]
I'd like to introduce qpl to boost deflate (de)compression for erofs-utils.
Is it possible to ship a dynamic library target together with the current static target?

**Comment by mzhukova** [comment]
Hi @hsiangkao, yes, we've actually got quite a few requests for introducing QPL dynamic library, so this is in the works.
I can't promise that it would be available with the next release, but should be ready some time soon.
I'll leave this issue open and notify you once ready!

**Comment by hsiangkao** [comment]
Hi @mzhukova, some new progress of this? It's somewhat necessary for many distro packaging like Debian though.

**Comment by mzhukova** [comment]
Hi @hsiangkao work on shared library support is still in progress, ETA is next QPL release, I will notify you in this thread once ready.

**Comment by mzhukova** [comment]
Shared library support is available at https://github.com/intel/qpl/commit/667d4744a3aa834a9934e3addb0a5a9e8d5eddf1.

**Comment by hsiangkao** [comment]
> Shared library support is available at [667d474](https://github.com/intel/qpl/commit/667d4744a3aa834a9934e3addb0a5a9e8d5eddf1).

thanks, good news! closed~
