### ISSUE TITLE
pkgconfig support

### ISSUE THREAD

**Issue by hsiangkao** [intel/qpl#32]
It would be great if libqpl built and installed a pkg-config .pc support file
since many open-source projects doesn't directly use cmake and pkg-config would be helpful.

**Comment by mzhukova** [comment]
Hi @hsiangkao, we will take a look at this after the next release. Thanks!

**Comment by mzhukova** [comment]
Hi @hsiangkao could you please clarify what QPL configuration you would be interested in for pkg-config support?
Would shared library and default QPL build (Release, loading libaccel-config.so with dlopen as opposed to require explicit linking) work for your needs?

**Comment by hsiangkao** [comment]
> Hi @hsiangkao could you please clarify what QPL configuration you would be interested in for pkg-config support? Would shared library and default QPL build (Release, loading libaccel-config.so with dlopen as opposed to require explicit linking) work for your needs?

Hi @mzhukova.  Yes, that is fine. As long as I could dynamic link libqpl.so, it doesn't matter to use whatever configuration since vendors could adjust themselves.. After a new libqpl version is released, I could also try to package this for Debian in my extra time.

**Comment by mzhukova** [comment]
Sounds good @hsiangkao, shared library and pkg-config support should be available in the upcoming QPL 1.5.0 release.

**Comment by mzhukova** [comment]
@hsiangkao shared library support is available starting with the https://github.com/intel/qpl/commit/667d4744a3aa834a9934e3addb0a5a9e8d5eddf1 and pkg-config support was introduced with https://github.com/intel/qpl/commit/ccb172bea47f8d538b3f3eff308cbd95f77808ff.

**Comment by hsiangkao** [comment]
> @hsiangkao shared library support is available starting with the [667d474](https://github.com/intel/qpl/commit/667d4744a3aa834a9934e3addb0a5a9e8d5eddf1) and pkg-config support was introduced with [ccb172b](https://github.com/intel/qpl/commit/ccb172bea47f8d538b3f3eff308cbd95f77808ff).

confirmed that it works, thanks!
