### ISSUE TITLE
Scan function to find multiple chars

### ISSUE THREAD

**Issue by Jae0504** [intel/qpl#35]
Hello, I have a question about the scan function. Can we find multiple chars by using the scan function? For example, finding 'ab' or 'abc' from the input file? 
I checked the code example from the QPL documentation and I think we can find a maximum of 4 chars with the scan function if we change src1_bit_width.

**Comment by mzhukova** [comment]
Hi @Jae0504, I am not sure I understood the goal completely, is the idea to supply "ab" as input and find either "a" or "b", or would you like to search for exactly "ab" sequence?

I would try to see whether any of sub-operations of scan, see documentation [here](https://intel.github.io/qpl/documentation/dev_guide_docs/c_use_cases/filter_ops/c_operations_op_scan.html) works for you.

**Comment by mzhukova** [comment]
No reply in quite some time, so closing the issue. Please, feel free to re-open if still relevant.
