### ISSUE TITLE
How to perform filter operations on a CSV/Parquet file

### ISSUE THREAD

**Issue by Johnnyjax** [intel/qpl#36]
Hello, I can't seem to find an example that reads from a CSV file to perform a filter operation like scan or extract. Does QPL support this? I know IAA works with in-memory databases, so does one have to convert to some format first supported by IAA? 

Thanks.

**Comment by mzhukova** [comment]
Hi @Johnnyjax , QPL doesn't support reading specific input formats, but rather reading a raw output, you'll need some sort of a wrapper function to parse CSV or any other format and input this into QPL.
You can check out our current examples for scan to see how to use QPL APIs at https://github.com/intel/qpl/blob/develop/examples/low-level-api/scan_for_specific_value_example.cpp.

**Comment by mzhukova** [comment]
Closing as no reply in a long time, please feel free to re-open if still relevant.
