### ISSUE TITLE
qpl tests/thread_tests/stress 编译失败

### ISSUE THREAD

**Issue by ydgdsnn** [intel/qpl#5]
1、编译环境信息： 
anolis 23  x86_64 环境
kernel version: 5.17.0
accel-config : 3.4.6.4
libgcc：12.1.0
gcc 12.1.0
gcc-c++ 12.1.0
gtest 1.21.1

2、按照 QPL 的操作指导，运行 cmake --build . --target install 时，提示如下错误：
![image](https://user-images.githubusercontent.com/57069943/196600175-a9a1655e-f4d3-4bf6-b2b7-257a8498500e.png)

3、初步排查：
查看 tools/tests/thread_tests/stress/CMakeFiles/stress_thread_tests.dir/build.make 里有相关内容：
![image](https://user-images.githubusercontent.com/57069943/196600352-9783c95c-ce55-43c5-bd54-4b5aecb1e319.png)

[root@iZbp11aoixmc85tz24lj8dZ build]# cd tools/tests/thread_tests/stress/
[root@iZbp11aoixmc85tz24lj8dZ stress]# cat CMakeFiles/stress_thread_tests.dir/link.txt
/usr/bin/c++ CMakeFiles/stress_thread_tests.dir/compressor_stress_test.cpp.o CMakeFiles/stress_thread_tests.dir/main.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/common_methods.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/configurator.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/indexed_stream/base_index.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/indexed_stream/incorrect_block_size.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/indexed_stream/mini_block_buffer_overflow.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/indexed_stream/mini_block_buffer_underflow.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/indexed_stream/no_error.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_block_configurators/bad_distance.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_block_configurators/bad_stored_length.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_block_configurators/distance_before_start.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_block_configurators/unallowable_d_code.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_block_configurators/unallowable_ll_code.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/big_repeat_count_d_codes.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/big_repeat_count_ll_codes.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/cl_codes_span_single_table.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/first_d_16_code.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/first_ll_16_code.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/invalid_block.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/large_header.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/many_distance_codes.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/many_distance_codes_v2.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/many_ll_codes.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/no_literal_length_code.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/oversubscribed_cl_tree.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/oversubscribed_d_tree.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/oversubscribed_ll_tree.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/break_header_configurators/undef_cl_code.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/correct_stream_generators/canned_large_ll_table.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/correct_stream_generators/canned_small_blocks.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/correct_stream_generators/dynamic_block_no_err.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/correct_stream_generators/fixed_block_no_err.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/correct_stream_generators/huffman_only.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/configurators/rfc1951_stream/correct_stream_generators/stored_block_no_err.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/crc_generator.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/bitbuffer.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/gen.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/grammar.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/histogram.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/huff_codes.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/huffman.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/token.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/deflate_generator/token_parcer.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/index_generator.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/index_table.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/inflate_generator.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/prle_generator.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/random_generator.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/uint_bit_stream.cpp.o ../../../utils/generators/CMakeFiles/tool_generator.dir/zero_generator.cpp.o -o stress_thread_tests  -lgtest ../../common/libtests_common.a ../../../../sources/cpp_api/libqplhl.a ../../../../sources/c_api/libqpl.a -ldl -lpthread -lstdc++fs -lgtest ../../../utils/common/libtool_common.a -lstdc++fs

**Comment by mzhukova** [comment]
Hi @ydgdsnn, could you please also provide an output of the `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<install_dir> ..` step, so that we could better understand if all the necessary tools were found during setup?

**Comment by mzhukova** [comment]
Hi @ydgdsnn, please let me know if the issue still exists of if it could be closed.

**Comment by mzhukova** [comment]
Hi @ydgdsnn, since we haven't heard back from you on details of the reproducer, I will be closing the issue.
