### ISSUE TITLE
指定iaa硬件进行压缩与解压

### ISSUE THREAD

**Issue by MansonHuaZ** [intel/qpl#6]
我有两个进程，进程1与进程2。我的服务器中有两个iaa硬件，iaa1与iaa3。
若我希望让进程1只调用iaa1进行压缩操作。进程2只调用iaa3进行解压操作。
在代码中应该如何编写，是否有响应的接口或者函数让我选择iaa硬件，然后再执行qpl_execute_job.

**Comment by MansonHuaZ** [comment]
I have two processes, process 1 and process 2. I have two iaa hardware in my server, iaa1 and iaa3.
If I want to let process 1 only call iaa1 for compression. Process 2 only calls iaa3 for decompression.
How should it be written in the code, is there an interface or function for me to choose the iaa hardware, and then execute the qpl_execute_job.

**Comment by mzhukova** [comment]
Hi @MansonHuaZ,
Currently QPL will grab whatever devices were made available (meaning if you configured a machine so that both IAA1 and IAA3 are available for execution, then both will be used). There is no API to assign particular task to a specific device as of now.
