### ISSUE TITLE
Can QPL provide a release package that can be built from directly

### ISSUE THREAD

**Issue by yaqi-zhao** [intel/qpl#9]
Can QPL provide a release that can be built from direct downloadable files (.tar, .tgz).
The current release packages has no google-test submodules.

**Comment by mzhukova** [comment]
Hi, this is addressed now at bbea8d110c2628fe9e1d6e4330d6840c4d225186, please use `-DQPL_BUILD_TESTS=OFF` in order to skip building tests and benchmarks executables (and therefore submodules, which are not included into `.tar`, `.tgz`).

**Comment by mzhukova** [comment]
@yaqi-zhao let me know once you try this out, so I can close the issue. Thanks!

**Comment by mzhukova** [comment]
Hi @yaqi-zhao could you please take a look at the recent changes and let me know if these resolve your issue?

**Comment by yaqi-zhao** [comment]
hi @mzhukova , the issue is solved  with -DQPL_BUILD_TESTS=OFF. Thanks a lot for your work!

**Comment by mzhukova** [comment]
> hi @mzhukova , the issue is solved with -DQPL_BUILD_TESTS=OFF. Thanks a lot for your work!

Thank you for the update! I'll close the issue then.
